AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ApiEndpoint:
    Type: String

  AuthRoleName:
    Type: String

  OpenIdAuthLayerArn:
    Type: String

  SecretArn:
    Type: String

  CodecsParameterName:
    Type: String

  ApiStackName:
    Type: String

  ParentStackName:
    Type: String

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Timeout: 30
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.13
    Architectures:
      - arm64

Resources:
  HlsManifestFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt HlsManifestFunction.Arn
      FunctionUrlAuthType: AWS_IAM
      Action: lambda:InvokeFunctionUrl
      Principal: !Sub "${AWS::AccountId}"

  AuthRolePolicyHls:
    Type: AWS::IAM::RolePolicy
    DependsOn: HlsManifestFunctionUrl
    Properties:
      RoleName: !Ref AuthRoleName
      PolicyName: !Ref AWS::StackName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunctionUrl
              - lambda:InvokeFunction
            Resource:
              - !GetAtt HlsManifestFunction.Arn

  HlsManifestFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: VPC not required
          - id: W92
            reason: ReservedConcurrentExecutions not required
    Properties:
      CodeUri: functions/hls-generator-lambda/
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
          AllowHeaders:
            - "*"
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python313-arm64:7
        - !Ref OpenIdAuthLayerArn
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: tams-tools
          POWERTOOLS_METRICS_NAMESPACE: TAMS-Tools
          TAMS_ENDPOINT: !Ref ApiEndpoint
          SECRET_ARN: !Ref SecretArn
          DEFAULT_HLS_SEGMENTS: 150
          CODEC_PARAMETER: !Ref CodecsParameterName
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref SecretArn
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${CodecsParameterName}

  HlsManifestFunctionSelfInvokePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${HlsManifestFunction}SelfInvoke"
      Roles:
        - !Ref HlsManifestFunctionRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunctionUrl
              - lambda:InvokeFunction
              - lambda:GetFunctionUrlConfig
            Resource:
              - !GetAtt HlsManifestFunction.Arn

Outputs:
  HlsFunctionUrl:
    Value: !GetAtt HlsManifestFunctionUrl.FunctionUrl
